export const countries = [
    { id: 840, iso2: "US", name: "United States" },
    { id: 124, iso2: "CA", name: "Canada" },
    { id: 710, iso2: "ZA", name: "South Africa" },
    { id: 826, iso2: "GB", name: "United Kingdom" },
    { id: 250, iso2: "FR", name: "France" },
    { id: 36, iso2: "AU", name: "Australia" },
    { id: 4, iso2: "AF", name: "Afghanistan" },
    { id: 248, iso2: "AX", name: "Aland Islands" },
    { id: 8, iso2: "AL", name: "Albania" },
    { id: 12, iso2: "DZ", name: "Algeria" },
    { id: 16, iso2: "AS", name: "American Samoa" },
    { id: 20, iso2: "AD", name: "Andorra" },
    { id: 24, iso2: "AO", name: "Angola" },
    { id: 660, iso2: "AI", name: "Anguilla" },
    { id: 10, iso2: "AQ", name: "Antarctica" },
    { id: 28, iso2: "AG", name: "Antigua and Barbuda" },
    { id: 32, iso2: "AR", name: "Argentina" },
    { id: 51, iso2: "AM", name: "Armenia" },
    { id: 533, iso2: "AW", name: "Aruba" },
    { id: 40, iso2: "AT", name: "Austria" },
    { id: 31, iso2: "AZ", name: "Azerbaijan" },
    { id: 44, iso2: "BS", name: "Bahamas" },
    { id: 48, iso2: "BH", name: "Bahrain" },
    { id: 50, iso2: "BD", name: "Bangladesh" },
    { id: 52, iso2: "BB", name: "Barbados" },
    { id: 112, iso2: "BY", name: "Belarus" },
    { id: 56, iso2: "BE", name: "Belgium" },
    { id: 84, iso2: "BZ", name: "Belize" },
    { id: 204, iso2: "BJ", name: "Benin" },
    { id: 60, iso2: "BM", name: "Bermuda" },
    { id: 64, iso2: "BT", name: "Bhutan" },
    { id: 68, iso2: "BO", name: "Bolivia" },
    { id: 70, iso2: "BA", name: "Bosnia and Herzegovina" },
    { id: 72, iso2: "BW", name: "Botswana" },
    { id: 74, iso2: "BV", name: "Bouvet Island" },
    { id: 76, iso2: "BR", name: "Brazil" },
    { id: 86, iso2: "IO", name: "British Indian Ocean Territory" },
    { id: 96, iso2: "BN", name: "Brunei Darussalam" },
    { id: 100, iso2: "BG", name: "Bulgaria" },
    { id: 854, iso2: "BF", name: "Burkina Faso" },
    { id: 108, iso2: "BI", name: "Burundi" },
    { id: 116, iso2: "KH", name: "Cambodia" },
    { id: 120, iso2: "CM", name: "Cameroon" },
    { id: 132, iso2: "CV", name: "Cape Verde" },
    { id: 136, iso2: "KY", name: "Cayman Islands" },
    { id: 140, iso2: "CF", name: "Central African Republic" },
    { id: 148, iso2: "TD", name: "Chad" },
    { id: 152, iso2: "CL", name: "Chile" },
    { id: 156, iso2: "CN", name: "China" },
    { id: 162, iso2: "CX", name: "Christmas Island" },
    { id: 166, iso2: "CC", name: "Cocos (Keeling) Islands" },
    { id: 170, iso2: "CO", name: "Colombia" },
    { id: 174, iso2: "KM", name: "Comoros" },
    { id: 178, iso2: "CG", name: "Congo" },
    { id: 180, iso2: "CD", name: "Congo, Democratic Republic of the" },
    { id: 184, iso2: "CK", name: "Cook Islands" },
    { id: 188, iso2: "CR", name: "Costa Rica" },
    { id: 384, iso2: "CI", name: "Côte d'Ivoire" },
    { id: 191, iso2: "HR", name: "Croatia" },
    { id: 192, iso2: "CU", name: "Cuba" },
    { id: 531, iso2: "CW", name: "Cura\u00e7ao" },
    { id: 196, iso2: "CY", name: "Cyprus" },
    { id: 203, iso2: "CZ", name: "Czech Republic" },
    { id: 208, iso2: "DK", name: "Denmark" },
    { id: 262, iso2: "DJ", name: "Djibouti" },
    { id: 212, iso2: "DM", name: "Dominica" },
    { id: 214, iso2: "DO", name: "Dominican Republic" },
    { id: 218, iso2: "EC", name: "Ecuador" },
    { id: 818, iso2: "EG", name: "Egypt" },
    { id: 222, iso2: "SV", name: "El Salvador" },
    { id: 226, iso2: "GQ", name: "Equatorial Guinea" },
    { id: 232, iso2: "ER", name: "Eritrea" },
    { id: 233, iso2: "EE", name: "Estonia" },
    { id: 231, iso2: "ET", name: "Ethiopia" },
    { id: 238, iso2: "FK", name: "Falkland Islands (Malvinas)" },
    { id: 234, iso2: "FO", name: "Faroe Islands" },
    { id: 242, iso2: "FJ", name: "Fiji" },
    { id: 246, iso2: "FI", name: "Finland" },
    { id: 254, iso2: "GF", name: "French Guiana" },
    { id: 258, iso2: "PF", name: "French Polynesia" },
    { id: 260, iso2: "TF", name: "French Southern Territories" },
    { id: 266, iso2: "GA", name: "Gabon" },
    { id: 270, iso2: "GM", name: "Gambia" },
    { id: 268, iso2: "GE", name: "Georgia" },
    { id: 276, iso2: "DE", name: "Germany" },
    { id: 288, iso2: "GH", name: "Ghana" },
    { id: 292, iso2: "GI", name: "Gibraltar" },
    { id: 300, iso2: "GR", name: "Greece" },
    { id: 304, iso2: "GL", name: "Greenland" },
    { id: 308, iso2: "GD", name: "Grenada" },
    { id: 312, iso2: "GP", name: "Guadeloupe" },
    { id: 316, iso2: "GU", name: "Guam" },
    { id: 320, iso2: "GT", name: "Guatemala" },
    { id: 831, iso2: "GG", name: "Guernsey" },
    { id: 324, iso2: "GN", name: "Guinea" },
    { id: 624, iso2: "GW", name: "Guinea-Bissau" },
    { id: 328, iso2: "GY", name: "Guyana" },
    { id: 332, iso2: "HT", name: "Haiti" },
    { id: 334, iso2: "HM", name: "Heard Island and McDonald Islands" },
    { id: 336, iso2: "VA", name: "Holy See (Vatican City State)" },
    { id: 340, iso2: "HN", name: "Honduras" },
    { id: 344, iso2: "HK", name: "Hong Kong" },
    { id: 348, iso2: "HU", name: "Hungary" },
    { id: 352, iso2: "IS", name: "Iceland" },
    { id: 356, iso2: "IN", name: "India" },
    { id: 360, iso2: "ID", name: "Indonesia" },
    { id: 364, iso2: "IR", name: "Iran, Islamic Republic of" },
    { id: 368, iso2: "IQ", name: "Iraq" },
    { id: 372, iso2: "IE", name: "Ireland" },
    { id: 833, iso2: "IM", name: "Isle of Man" },
    { id: 376, iso2: "IL", name: "Israel" },
    { id: 380, iso2: "IT", name: "Italy" },
    { id: 388, iso2: "JM", name: "Jamaica" },
    { id: 392, iso2: "JP", name: "Japan" },
    { id: 832, iso2: "JE", name: "Jersey" },
    { id: 400, iso2: "JO", name: "Jordan" },
    { id: 398, iso2: "KZ", name: "Kazakhstan" },
    { id: 404, iso2: "KE", name: "Kenya" },
    { id: 296, iso2: "KI", name: "Kiribati" },
    { id: 408, iso2: "KP", name: "Korea, Democratic People\\'s Republic of" },
    { id: 410, iso2: "KR", name: "South Korea" },
    { id: 414, iso2: "KW", name: "Kuwait" },
    { id: 417, iso2: "KG", name: "Kyrgyzstan" },
    { id: 418, iso2: "LA", name: "Lao People\\'s Democratic Republic" },
    { id: 428, iso2: "LV", name: "Latvia" },
    { id: 422, iso2: "LB", name: "Lebanon" },
    { id: 426, iso2: "LS", name: "Lesotho" },
    { id: 430, iso2: "LR", name: "Liberia" },
    { id: 434, iso2: "LY", name: "Libyan Arab Jamahiriya" },
    { id: 438, iso2: "LI", name: "Liechtenstein" },
    { id: 440, iso2: "LT", name: "Lithuania" },
    { id: 442, iso2: "LU", name: "Luxembourg" },
    { id: 446, iso2: "MO", name: "Macao" },
    { id: 807, iso2: "MK", name: "Macedonia, the former Yugoslav Republic of" },
    { id: 450, iso2: "MG", name: "Madagascar" },
    { id: 454, iso2: "MW", name: "Malawi" },
    { id: 458, iso2: "MY", name: "Malaysia" },
    { id: 462, iso2: "MV", name: "Maldives" },
    { id: 466, iso2: "ML", name: "Mali" },
    { id: 470, iso2: "MT", name: "Malta" },
    { id: 584, iso2: "MH", name: "Marshall Islands" },
    { id: 474, iso2: "MQ", name: "Martinique" },
    { id: 478, iso2: "MR", name: "Mauritania" },
    { id: 480, iso2: "MU", name: "Mauritius" },
    { id: 175, iso2: "YT", name: "Mayotte" },
    { id: 484, iso2: "MX", name: "Mexico" },
    { id: 583, iso2: "FM", name: "Micronesia, Federated States of" },
    { id: 498, iso2: "MD", name: "Moldova" },
    { id: 492, iso2: "MC", name: "Monaco" },
    { id: 496, iso2: "MN", name: "Mongolia" },
    { id: 499, iso2: "ME", name: "Montenegro" },
    { id: 500, iso2: "MS", name: "Montserrat" },
    { id: 504, iso2: "MA", name: "Morocco" },
    { id: 508, iso2: "MZ", name: "Mozambique" },
    { id: 104, iso2: "MM", name: "Myanmar" },
    { id: 516, iso2: "NA", name: "Namibia" },
    { id: 520, iso2: "NR", name: "Nauru" },
    { id: 524, iso2: "NP", name: "Nepal" },
    { id: 528, iso2: "NL", name: "Netherlands" },
    { id: 540, iso2: "NC", name: "New Caledonia" },
    { id: 554, iso2: "NZ", name: "New Zealand" },
    { id: 558, iso2: "NI", name: "Nicaragua" },
    { id: 562, iso2: "NE", name: "Niger" },
    { id: 566, iso2: "NG", name: "Nigeria" },
    { id: 570, iso2: "NU", name: "Niue" },
    { id: 574, iso2: "NF", name: "Norfolk Island" },
    { id: 580, iso2: "MP", name: "Northern Mariana Islands" },
    { id: 578, iso2: "NO", name: "Norway" },
    { id: 512, iso2: "OM", name: "Oman" },
    { id: 586, iso2: "PK", name: "Pakistan" },
    { id: 585, iso2: "PW", name: "Palau" },
    { id: 275, iso2: "PS", name: "Palestinian Territory, Occupied" },
    { id: 591, iso2: "PA", name: "Panama" },
    { id: 598, iso2: "PG", name: "Papua New Guinea" },
    { id: 600, iso2: "PY", name: "Paraguay" },
    { id: 604, iso2: "PE", name: "Peru" },
    { id: 608, iso2: "PH", name: "Philippines" },
    { id: 612, iso2: "PN", name: "Pitcairn" },
    { id: 616, iso2: "PL", name: "Poland" },
    { id: 620, iso2: "PT", name: "Portugal" },
    { id: 630, iso2: "PR", name: "Puerto Rico" },
    { id: 634, iso2: "QA", name: "Qatar" },
    { id: 383, iso2: "XK", name: "Republic of Kosovo" },
    { id: 638, iso2: "RE", name: "Réunion" },
    { id: 642, iso2: "RO", name: "Romania" },
    { id: 643, iso2: "RU", name: "Russian Federation" },
    { id: 646, iso2: "RW", name: "Rwanda" },
    { id: 652, iso2: "BL", name: "Saint Barth" },
    { id: 654, iso2: "SH", name: "Saint Helena" },
    { id: 659, iso2: "KN", name: "Saint Kitts and Nevis" },
    { id: 662, iso2: "LC", name: "Saint Lucia" },
    { id: 663, iso2: "MF", name: "Saint Martin (French part)" },
    { id: 666, iso2: "PM", name: "Saint Pierre and Miquelon" },
    { id: 670, iso2: "VC", name: "Saint Vincent and the Grenadines" },
    { id: 882, iso2: "WS", name: "Samoa" },
    { id: 674, iso2: "SM", name: "San Marino" },
    { id: 678, iso2: "ST", name: "Sao Tome and Principe" },
    { id: 682, iso2: "SA", name: "Saudi Arabia" },
    { id: 686, iso2: "SN", name: "Senegal" },
    { id: 688, iso2: "RS", name: "Serbia" },
    { id: 690, iso2: "SC", name: "Seychelles" },
    { id: 694, iso2: "SL", name: "Sierra Leone" },
    { id: 702, iso2: "SG", name: "Singapore" },
    { id: 534, iso2: "SX", name: "SINT MAARTEN" },
    { id: 703, iso2: "SK", name: "Slovakia" },
    { id: 705, iso2: "SI", name: "Slovenia" },
    { id: 90, iso2: "SB", name: "Solomon Islands" },
    { id: 706, iso2: "SO", name: "Somalia" },
    { id: 239, iso2: "GS", name: "South Georgia and the South Sandwich Islands" },
    { id: 724, iso2: "ES", name: "Spain" },
    { id: 144, iso2: "LK", name: "Sri Lanka" },
    { id: 736, iso2: "SD", name: "Sudan" },
    { id: 740, iso2: "SR", name: "Suriname" },
    { id: 744, iso2: "SJ", name: "Svalbard and Jan Mayen" },
    { id: 748, iso2: "SZ", name: "Swaziland" },
    { id: 752, iso2: "SE", name: "Sweden" },
    { id: 756, iso2: "CH", name: "Switzerland" },
    { id: 760, iso2: "SY", name: "Syrian Arab Republic" },
    { id: 158, iso2: "TW", name: "Taiwan, Province of China" },
    { id: 762, iso2: "TJ", name: "Tajikistan" },
    { id: 834, iso2: "TZ", name: "Tanzania, United Republic of" },
    { id: 764, iso2: "TH", name: "Thailand" },
    { id: 626, iso2: "TL", name: "Timor-Leste" },
    { id: 768, iso2: "TG", name: "Togo" },
    { id: 772, iso2: "TK", name: "Tokelau" },
    { id: 776, iso2: "TO", name: "Tonga" },
    { id: 780, iso2: "TT", name: "Trinidad and Tobago" },
    { id: 788, iso2: "TN", name: "Tunisia" },
    { id: 792, iso2: "TR", name: "Turkey" },
    { id: 795, iso2: "TM", name: "Turkmenistan" },
    { id: 796, iso2: "TC", name: "Turks and Caicos Islands" },
    { id: 798, iso2: "TV", name: "Tuvalu" },
    { id: 800, iso2: "UG", name: "Uganda" },
    { id: 804, iso2: "UA", name: "Ukraine" },
    { id: 784, iso2: "AE", name: "United Arab Emirates" },
    { id: 581, iso2: "UM", name: "United States Minor Outlying Islands" },
    { id: 858, iso2: "UY", name: "Uruguay" },
    { id: 860, iso2: "UZ", name: "Uzbekistan" },
    { id: 548, iso2: "VU", name: "Vanuatu" },
    { id: 862, iso2: "VE", name: "Venezuela" },
    { id: 704, iso2: "VN", name: "Viet Nam" },
    { id: 92, iso2: "VG", name: "Virgin Islands, British" },
    { id: 850, iso2: "VI", name: "Virgin Islands, U.S." },
    { id: 876, iso2: "WF", name: "Wallis and Futuna" },
    { id: 732, iso2: "EH", name: "Western Sahara" },
    { id: 887, iso2: "YE", name: "Yemen" },
    { id: 894, iso2: "ZM", name: "Zambia" },
    { id: 716, iso2: "ZW", name: "Zimbabwe" },
];

export const states = {
    840: [
        { regionIso2: "AA", id: 840, name: "Armed Forces Americas" },
        { regionIso2: "AE", id: 840, name: "Armed Forces Europe, Middle East, & Canada" },
        { regionIso2: "AK", id: 840, name: "Alaska" },
        { regionIso2: "AL", id: 840, name: "Alabama" },
        { regionIso2: "AP", id: 840, name: "Armed Forces Pacific" },
        { regionIso2: "AR", id: 840, name: "Arkansas" },
        { regionIso2: "AS", id: 840, name: "American Samoa" },
        { regionIso2: "AZ", id: 840, name: "Arizona" },
        { regionIso2: "CA", id: 840, name: "California" },
        { regionIso2: "CO", id: 840, name: "Colorado" },
        { regionIso2: "CT", id: 840, name: "Connecticut" },
        { regionIso2: "DC", id: 840, name: "District of Columbia" },
        { regionIso2: "DE", id: 840, name: "Delaware" },
        { regionIso2: "FL", id: 840, name: "Florida" },
        { regionIso2: "FM", id: 840, name: "Federated States of Micronesia" },
        { regionIso2: "GA", id: 840, name: "Georgia" },
        { regionIso2: "GU", id: 840, name: "Guam" },
        { regionIso2: "HI", id: 840, name: "Hawaii" },
        { regionIso2: "IA", id: 840, name: "Iowa" },
        { regionIso2: "ID", id: 840, name: "Idaho" },
        { regionIso2: "IL", id: 840, name: "Illinois" },
        { regionIso2: "IN", id: 840, name: "Indiana" },
        { regionIso2: "KS", id: 840, name: "Kansas" },
        { regionIso2: "KY", id: 840, name: "Kentucky" },
        { regionIso2: "LA", id: 840, name: "Louisiana" },
        { regionIso2: "MA", id: 840, name: "Massachusetts" },
        { regionIso2: "MD", id: 840, name: "Maryland" },
        { regionIso2: "ME", id: 840, name: "Maine" },
        { regionIso2: "MH", id: 840, name: "Marshall Islands" },
        { regionIso2: "MI", id: 840, name: "Michigan" },
        { regionIso2: "MN", id: 840, name: "Minnesota" },
        { regionIso2: "MO", id: 840, name: "Missouri" },
        { regionIso2: "MP", id: 840, name: "Northern Mariana Islands" },
        { regionIso2: "MS", id: 840, name: "Mississippi" },
        { regionIso2: "MT", id: 840, name: "Montana" },
        { regionIso2: "NC", id: 840, name: "North Carolina" },
        { regionIso2: "ND", id: 840, name: "North Dakota" },
        { regionIso2: "NE", id: 840, name: "Nebraska" },
        { regionIso2: "NH", id: 840, name: "New Hampshire" },
        { regionIso2: "NJ", id: 840, name: "New Jersey" },
        { regionIso2: "NM", id: 840, name: "New Mexico" },
        { regionIso2: "NV", id: 840, name: "Nevada" },
        { regionIso2: "NY", id: 840, name: "New York" },
        { regionIso2: "OH", id: 840, name: "Ohio" },
        { regionIso2: "OK", id: 840, name: "Oklahoma" },
        { regionIso2: "OR", id: 840, name: "Oregon" },
        { regionIso2: "PA", id: 840, name: "Pennsylvania" },
        { regionIso2: "PR", id: 840, name: "Puerto Rico" },
        { regionIso2: "PW", id: 840, name: "Palau" },
        { regionIso2: "RI", id: 840, name: "Rhode Island" },
        { regionIso2: "SC", id: 840, name: "South Carolina" },
        { regionIso2: "SD", id: 840, name: "South Dakota" },
        { regionIso2: "TN", id: 840, name: "Tennessee" },
        { regionIso2: "TX", id: 840, name: "Texas" },
        { regionIso2: "UT", id: 840, name: "Utah" },
        { regionIso2: "VA", id: 840, name: "Virginia" },
        { regionIso2: "VT", id: 840, name: "Vermont" },
        { regionIso2: "WA", id: 840, name: "Washington" },
        { regionIso2: "WI", id: 840, name: "Wisconsin" },
        { regionIso2: "WV", id: 840, name: "West Virginia" },
        { regionIso2: "WY", id: 840, name: "Wyoming" },
    ],
    124: [
        { regionIso2: "AB", id: 124, name: "Alberta" },
        { regionIso2: "BC", id: 124, name: "British Columbia" },
        { regionIso2: "MB", id: 124, name: "Manitoba" },
        { regionIso2: "NB", id: 124, name: "New Brunswick" },
        { regionIso2: "NL", id: 124, name: "Newfoundland" },
        { regionIso2: "NS", id: 124, name: "Nova Scotia" },
        { regionIso2: "NT", id: 124, name: "Northwest Territories" },
        { regionIso2: "NU", id: 124, name: "Nunavut" },
        { regionIso2: "ON", id: 124, name: "Ontario" },
        { regionIso2: "PE", id: 124, name: "Prince Edward Island" },
        { regionIso2: "QC", id: 124, name: "Quebec" },
        { regionIso2: "SK", id: 124, name: "Saskatchewan" },
        { regionIso2: "YT", id: 124, name: "Yukon Territory" },
    ],
};
